openapi: 3.0.1
info:
  title: Product Data Hub API
  description: 'REST API for Henkel RAQN Product Data Hub<br/><br/>Attributes of type ''string'' that represent timestamps are in ISO-8601 format, with the time zone set to ''Z'' (UTC).<br/>_Example_: 2023-03-06T13:41:12.507Z'
  license:
    name: Henkel AG & Co. KGaA
    url: https://henkel.de
  version: v1 [build# 20240605.2]
servers:
  - url: /pdh
    description: Generated server url
tags:
  - name: Catalog
    description: Products, Variants, Categories
paths:
  /api/v1/catalogs:
    get:
      tags:
        - Catalog
      summary: All catalogs
      description: Get all catalogs.
      operationId: catalogs
      responses:
        '200':
          description: All catalogs that currently exist in the database
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Catalog'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
  /api/v1/catalogs/{id}:
    get:
      tags:
        - Catalog
      summary: A single catalog
      description: Get a single catalog.
      operationId: catalog
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: gc_industrial|online
      responses:
        '200':
          description: The catalog for the given id.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Catalog'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '404':
          description: Not found. We can't find the requested resource.
          content:
            application/json:
              examples:
                404 Not Found:
                  description: 404 Not Found
                  value:
                    timestamp: '2021-11-25T10:27:00.087+00:00'
                    status: 404
                    error: Not Found
                    message: Catalog not found for id 'gc_industrial|stage' and lang 'en_US'
                    path: /api/v1/catalogs/gc_industrial|stage
  /api/v1/catalogs/{catalogId}/variants:
    get:
      tags:
        - Catalog
      summary: All product variants from a catalog
      description: Get all product variants. The response represents a chunk, i.e. a subset of all items; the chunk size can be controlled by the 'maxItems' parameters. See the 'x-req-continuation' request/response headers on how to request subsequent chunks and iterate over all items.
      operationId: variants
      parameters:
        - name: catalogId
          in: path
          required: true
          schema:
            type: string
          example: gc_industrial|online
        - name: lang
          in: query
          required: true
          schema:
            type: string
          example: en_US
        - name: modifiedAfter
          in: query
          description: If given, only variants are returned that were modified afterwards (excl.).
          required: false
          schema:
            type: string
            format: date-time
          example: '2024-01-01T12:00:00Z'
        - name: modifiedBefore
          in: query
          description: If given, only variants are returned that were modified before (excl.).
          required: false
          schema:
            type: string
            format: date-time
          example: '2034-01-01T12:00:00Z'
        - name: gtin
          in: query
          description: If given, only variants with that GTIN are returned.
          required: false
          schema:
            type: string
        - name: embedBaseProducts
          in: query
          description: If true, respond with base products embedded.
          required: false
          schema:
            type: boolean
            default: false
        - name: maxItems
          in: query
          description: Maximum number of items to include in response ('chunk size'). The actual number of returned items may be smaller. Also see the 'x-req-continuation' header ('chunk offset')
          required: false
          schema:
            maximum: 100
            minimum: 1
            type: integer
            format: int32
            default: 100
          example: 100
        - name: x-req-continuation
          in: header
          description: Get the next chunk of items - continue iterating over all items by going on with the subsequent chunk. To identify the previous chunk, pass the JSON string returned in the 'x-req-continuation' response header of the previous request. If the value is not present, the response will contain the first chunk.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: All variant products that currently exist in the catalog, together with their base product
          headers:
            x-req-total-items:
              description: Total number of items.
              style: simple
              schema:
                type: integer
            x-req-continuation:
              description: Present only if the current chunk of items is not the last one, so that iteration over all items can be continued. See the correspondent request header of the same name.
              style: simple
              schema:
                type: string
            x-req-chunk-items:
              description: Number of items on the current chunk.
              style: simple
              schema:
                type: integer
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  oneOf:
                    - $ref: '#/components/schemas/AdhesiveVariantProduct'
                    - $ref: '#/components/schemas/ConsumerBrandsVariantProduct'
        '400':
          description: Bad request, e.g. the 'lang' parameter was missing or unsupported
          content:
            application/json:
              examples:
                Unsupported language:
                  description: Unsupported language
                  value:
                    violations:
                      - fieldName: catalogs.lang
                        message: 'Unsupported language ''xx_XX'' for catalog: ''catalog'''
                Language not specified:
                  description: Language not specified
                  value:
                    violations:
                      - fieldName: request parameter 'lang'
                        message: Required request parameter 'lang' for method parameter type String is not present
  /api/v1/catalogs/{catalogId}/variants/{idh}:
    get:
      tags:
        - Catalog
      summary: A single product variant
      description: Get a single product variant (with base product).
      operationId: variant
      parameters:
        - name: catalogId
          in: path
          required: true
          schema:
            type: string
          example: gc_industrial|online
        - name: lang
          in: query
          required: true
          schema:
            type: string
          example: en_US
        - name: idh
          in: path
          required: true
          schema:
            type: string
        - name: embedBaseProduct
          in: query
          description: If true, respond with base product embedded.
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: The product variant for the given language and id, with base product.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/AdhesiveVariantProduct'
                  - $ref: '#/components/schemas/ConsumerBrandsVariantProduct'
        '400':
          description: Bad request, e.g. the 'lang' parameter was missing or unsupported
          content:
            application/json:
              examples:
                Unsupported language:
                  description: Unsupported language
                  value:
                    violations:
                      - fieldName: catalogs.lang
                        message: 'Unsupported language ''xx_XX'' for catalog: ''catalog'''
                Language not specified:
                  description: Language not specified
                  value:
                    violations:
                      - fieldName: request parameter 'lang'
                        message: Required request parameter 'lang' for method parameter type String is not present
        '404':
          description: Not found. We can't find the requested resource.
          content:
            application/json:
              examples:
                404 Not Found:
                  description: 404 Not Found
                  value:
                    timestamp: '2021-11-25T10:27:00.087+00:00'
                    status: 404
                    error: Not Found
                    message: Category not found for catalog 'gc_industrial|stage', id '1234' and lang 'en_US'
                    path: /api/v1/catalogs/gc_industrial|stage/1234
  /api/v1/catalogs/{catalogId}/products:
    get:
      tags:
        - Catalog
      summary: All base products from a catalog
      description: Get all products (base products with variants). The response represents a chunk, i.e. a subset of all items; the chunk size can be controlled by the 'maxItems' parameters. See the 'x-req-continuation' request/response headers on how to request subsequent chunks and iterate over all items.
      operationId: products
      parameters:
        - name: catalogId
          in: path
          required: true
          schema:
            type: string
          example: gc_industrial|online
        - name: lang
          in: query
          required: true
          schema:
            type: string
          example: en_US
        - name: modifiedAfter
          in: query
          description: If given, only products are returned that were modified afterwards (excl.).
          required: false
          schema:
            type: string
            format: date-time
          example: '2024-01-01T12:00:00Z'
        - name: modifiedBefore
          in: query
          description: If given, only products are returned that were modified before (excl.).
          required: false
          schema:
            type: string
            format: date-time
          example: '2034-01-01T12:00:00Z'
        - name: category
          in: query
          description: If given, only products are returned that are assigned to that category
          required: false
          schema:
            type: string
        - name: embedVariants
          in: query
          description: If true, respond with variants embedded.
          required: false
          schema:
            type: boolean
            default: false
        - name: embedCategories
          in: query
          description: If true, respond with categories embedded.
          required: false
          schema:
            type: boolean
            default: false
        - name: maxItems
          in: query
          description: Maximum number of items to include in response ('chunk size'). The actual number of returned items may be smaller. Also see the 'x-req-continuation' header ('chunk offset')
          required: false
          schema:
            maximum: 100
            minimum: 1
            type: integer
            format: int32
            default: 100
          example: 100
        - name: x-req-continuation
          in: header
          description: Get the next chunk of items - continue iterating over all items by going on with the subsequent chunk. To identify the previous chunk, pass the JSON string returned in the 'x-req-continuation' response header of the previous request. If the value is not present, the response will contain the first chunk.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: All base products that currently exist in the catalog, together with their variants
          headers:
            x-req-total-items:
              description: Total number of items.
              style: simple
              schema:
                type: integer
            x-req-continuation:
              description: Present only if the current chunk of items is not the last one, so that iteration over all items can be continued. See the correspondent request header of the same name.
              style: simple
              schema:
                type: string
            x-req-chunk-items:
              description: Number of items on the current chunk.
              style: simple
              schema:
                type: integer
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  oneOf:
                    - $ref: '#/components/schemas/AdhesiveBaseProduct'
                    - $ref: '#/components/schemas/ConsumerBrandsBaseProduct'
        '400':
          description: Bad request, e.g. the 'lang' parameter was missing or unsupported
          content:
            application/json:
              examples:
                Unknown category:
                  description: Unknown category
                  value:
                    timestamp: '2021-12-02T10:46:22.502+00:00'
                    status: 400
                    error: Bad Request
                    message: Unknown category 'xxx'
                    path: /api/v1/catalogs/gc_industrial%7Conline/products
                Unsupported language:
                  description: Unsupported language
                  value:
                    violations:
                      - fieldName: catalogs.lang
                        message: 'Unsupported language ''xx_XX'' for catalog: ''catalog'''
                Language not specified:
                  description: Language not specified
                  value:
                    violations:
                      - fieldName: request parameter 'lang'
                        message: Required request parameter 'lang' for method parameter type String is not present
  /api/v1/catalogs/{catalogId}/products/{id}:
    get:
      tags:
        - Catalog
      summary: A single base product
      description: Get a single product (base product with variants).
      operationId: product
      parameters:
        - name: catalogId
          in: path
          required: true
          schema:
            type: string
          example: gc_industrial|online
        - name: lang
          in: query
          required: true
          schema:
            type: string
          example: en_US
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: embedVariants
          in: query
          description: If true, respond with variants embedded.
          required: false
          schema:
            type: boolean
            default: false
        - name: embedCategories
          in: query
          description: If true, respond with categories embedded.
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: The base product for the given language and id, with variants.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/AdhesiveBaseProduct'
                  - $ref: '#/components/schemas/ConsumerBrandsBaseProduct'
        '400':
          description: Bad request, e.g. the 'lang' parameter was missing or unsupported
          content:
            application/json:
              examples:
                Unsupported language:
                  description: Unsupported language
                  value:
                    violations:
                      - fieldName: catalogs.lang
                        message: 'Unsupported language ''xx_XX'' for catalog: ''catalog'''
                Language not specified:
                  description: Language not specified
                  value:
                    violations:
                      - fieldName: request parameter 'lang'
                        message: Required request parameter 'lang' for method parameter type String is not present
        '404':
          description: Not found. We can't find the requested resource.
          content:
            application/json:
              examples:
                404 Not Found:
                  description: 404 Not Found
                  value:
                    timestamp: '2021-11-25T10:27:00.087+00:00'
                    status: 404
                    error: Not Found
                    message: Category not found for catalog 'gc_industrial|stage', id '1234' and lang 'en_US'
                    path: /api/v1/catalogs/gc_industrial|stage/1234
  /api/v1/catalogs/{catalogId}/categories:
    get:
      tags:
        - Catalog
      summary: All categories from a catalog
      description: Get all categories.
      operationId: categories
      parameters:
        - name: catalogId
          in: path
          required: true
          schema:
            type: string
          example: gc_industrial|online
        - name: lang
          in: query
          required: true
          schema:
            type: string
          example: en_US
        - name: type
          in: query
          description: If given, only categories of that type are returned.
          required: false
          schema:
            type: string
          examples:
            Industry:
              description: Industry
              value: Industry
            Technology:
              description: Technology
              value: Technology
            HenkelProductType:
              description: HenkelProductType
              value: HenkelProductType
      responses:
        '200':
          description: All categories that currently exist in the catalog
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        '400':
          description: Bad request, e.g. the 'lang' parameter was missing or unsupported
          content:
            application/json:
              examples:
                Unsupported language:
                  description: Unsupported language
                  value:
                    violations:
                      - fieldName: catalogs.lang
                        message: 'Unsupported language ''xx_XX'' for catalog: ''catalog'''
                Language not specified:
                  description: Language not specified
                  value:
                    violations:
                      - fieldName: request parameter 'lang'
                        message: Required request parameter 'lang' for method parameter type String is not present
  /api/v1/catalogs/{catalogId}/categories/{id}:
    get:
      tags:
        - Catalog
      summary: A single category
      description: Get a single category.
      operationId: category
      parameters:
        - name: catalogId
          in: path
          required: true
          schema:
            type: string
          example: gc_industrial|online
        - name: lang
          in: query
          required: true
          schema:
            type: string
          example: en_US
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: embedChildren
          in: query
          description: If true, respond with child categories embedded.
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: The category for the given language and id.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '400':
          description: Bad request, e.g. the 'lang' parameter was missing or unsupported
          content:
            application/json:
              examples:
                Unsupported language:
                  description: Unsupported language
                  value:
                    violations:
                      - fieldName: catalogs.lang
                        message: 'Unsupported language ''xx_XX'' for catalog: ''catalog'''
                Language not specified:
                  description: Language not specified
                  value:
                    violations:
                      - fieldName: request parameter 'lang'
                        message: Required request parameter 'lang' for method parameter type String is not present
        '404':
          description: Not found. We can't find the requested resource.
          content:
            application/json:
              examples:
                404 Not Found:
                  description: 404 Not Found
                  value:
                    timestamp: '2021-11-25T10:27:00.087+00:00'
                    status: 404
                    error: Not Found
                    message: Category not found for catalog 'gc_industrial|stage', id '1234' and lang 'en_US'
                    path: /api/v1/catalogs/gc_industrial|stage/1234
components:
  schemas:
    ValidationErrorResponse:
      type: object
      properties:
        violations:
          type: array
          items:
            $ref: '#/components/schemas/Violation'
    Violation:
      type: object
      properties:
        fieldName:
          type: string
        message:
          type: string
    Catalog:
      type: object
      properties:
        id:
          type: string
          example: gc_industrial|online
        modified:
          type: string
          format: date-time
        bu:
          type: string
          example: A
        name:
          type: string
        languages:
          type: array
          items:
            type: string
    AdhesiveVariantProduct:
      type: object
      properties:
        id:
          type: string
        modified:
          type: string
          format: date-time
        deleted:
          type: boolean
        lang:
          type: string
          example: en_US
        catalogId:
          type: string
          example: gc_industrial|online
        categoryIds:
          type: array
          items:
            type: string
        attributes:
          $ref: /pdh/oas/product_attributes.json#/components/schemas/AdhesiveVariantProductAttributes
        baseProduct:
          $ref: '#/components/schemas/BaseProduct'
        baseProductId:
          type: string
        consumerGtin:
          type: string
        gtins:
          type: array
          items:
            type: string
    BaseProduct:
      type: object
      properties:
        id:
          type: string
        modified:
          type: string
          format: date-time
        deleted:
          type: boolean
        lang:
          type: string
          example: en_US
        catalogId:
          type: string
          example: gc_industrial|online
        categoryIds:
          type: array
          items:
            type: string
        attributes:
          type: object
          additionalProperties:
            type: object
        variantIdhs:
          type: array
          items:
            type: string
        categories:
          type: array
          items:
            $ref: '#/components/schemas/Category'
    Category:
      type: object
      properties:
        id:
          type: string
          example: industry_2.4.11.2
        modified:
          type: string
          format: date-time
        deleted:
          type: boolean
        parent:
          type: string
          description: ''''' (empty string) in case of a top-level category'
          example: industry_2.4.11
        children:
          type: array
          description: child categories IDs
          items:
            type: string
            description: child categories IDs
        childCategories:
          type: array
          description: child categories embedded (optional)
          items:
            $ref: '#/components/schemas/Category'
        lang:
          type: string
          example: en_US
        level:
          type: integer
          format: int32
          example: 42
        active:
          type: boolean
          description: Categories with active=false are currently not being used.
          example: true
        catalogId:
          type: string
          example: gc_industrial|online
        name:
          type: string
        type:
          type: string
          example: Industry
        owner:
          type: string
          description: Possible values INDUSTRIAL, CONSUMER - only for Industry, HenkelProductType.
          example: CONSUMER
        images:
          type: array
          items:
            type: object
            additionalProperties:
              type: object
        sbu:
          $ref: '#/components/schemas/ReferenceData'
        attributes:
          type: object
          additionalProperties:
            type: object
    ReferenceData:
      type: object
      properties:
        code:
          type: string
        name:
          type: string
      description: Code and name of the SBU
    VariantProduct:
      type: object
      properties:
        id:
          type: string
        modified:
          type: string
          format: date-time
        deleted:
          type: boolean
        lang:
          type: string
          example: en_US
        catalogId:
          type: string
          example: gc_industrial|online
        categoryIds:
          type: array
          items:
            type: string
        attributes:
          type: object
          additionalProperties:
            type: object
        baseProduct:
          $ref: '#/components/schemas/BaseProduct'
        baseProductId:
          type: string
        consumerGtin:
          type: string
        gtins:
          type: array
          items:
            type: string
    ConsumerBrandsVariantProduct:
      type: object
      properties:
        id:
          type: string
        modified:
          type: string
          format: date-time
        deleted:
          type: boolean
        lang:
          type: string
          example: en_US
        catalogId:
          type: string
          example: gc_industrial|online
        categoryIds:
          type: array
          items:
            type: string
        attributes:
          $ref: /pdh/oas/product_attributes.json#/components/schemas/ConsumerBrandsVariantProductAttributes
        baseProduct:
          $ref: '#/components/schemas/BaseProduct'
        baseProductId:
          type: string
        consumerGtin:
          type: string
        gtins:
          type: array
          items:
            type: string
    AdhesiveBaseProduct:
      type: object
      properties:
        id:
          type: string
        modified:
          type: string
          format: date-time
        deleted:
          type: boolean
        lang:
          type: string
          example: en_US
        catalogId:
          type: string
          example: gc_industrial|online
        categoryIds:
          type: array
          items:
            type: string
        attributes:
          $ref: /pdh/oas/product_attributes.json#/components/schemas/AdhesiveBaseProductAttributes
        variants:
          type: array
          items:
            $ref: '#/components/schemas/VariantProduct'
        variantIdhs:
          type: array
          items:
            type: string
        categories:
          type: array
          items:
            $ref: '#/components/schemas/Category'
    ConsumerBrandsBaseProduct:
      type: object
      properties:
        id:
          type: string
        modified:
          type: string
          format: date-time
        deleted:
          type: boolean
        lang:
          type: string
          example: en_US
        catalogId:
          type: string
          example: gc_industrial|online
        categoryIds:
          type: array
          items:
            type: string
        attributes:
          $ref: /pdh/oas/product_attributes.json#/components/schemas/ConsumerBrandsBaseProductAttributes
        variants:
          type: array
          items:
            $ref: '#/components/schemas/VariantProduct'
        variantIdhs:
          type: array
          items:
            type: string
        categories:
          type: array
          items:
            $ref: '#/components/schemas/Category'
    Digest:
      type: object
      properties:
        idh:
          type: string
        idhName:
          type: string
        baseProductId:
          type: string
        baseProductName:
          type: string
        sbu:
          type: string
        brand:
          type: string
        categories:
          type: array
          items:
            type: string
        industry:
          type: string
        productCategory:
          type: string
        salesAreaData:
          type: array
          items:
            $ref: '#/components/schemas/SalesAreaData'
        overallActive:
          type: boolean
        productStatus:
          type: string
    ReferenceCode:
      type: object
      properties:
        code:
          type: string
    SalesAreaData:
      type: object
      properties:
        salesArea:
          $ref: '#/components/schemas/ReferenceCode'
        getyStatus:
          $ref: '#/components/schemas/ReferenceCode'
    CategoryDigest:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        owner:
          type: string
